
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockstatuss-deployment1
  labels: 
    name: finalproject-pod
    dev: sara
  namespace: k8s-deploy-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      name: finalproject-pod
      dev: sara
  template:
    metadata: 
      name: finalproject-pod
      labels:
        name: finalproject-pod
        dev: sara
    spec: 
      containers:
      - name: finalproject-container
        image: saravanann07/finalprojectserver:v.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: finalproject-secret

---
apiVersion: v1
kind: Service
metadata:
  name: finalproject-svc-lb
  namespace: k8s-deploy-ns
spec:
  type: LoadBalancer
  selector:
    name: finalproject-pod
    dev: sara
  ports: 
  - name: p80
    port: 80
    targetPort: 8080